/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Panel;
import java.awt.TextField;
import java.io.*;
import javax.swing.*;
import Clases.*;

/**
 *
 * @author sebas
 */
public class Resultados extends javax.swing.JFrame {
    private JTextArea campo2;
    private JScrollPane scroll;
    /**
     * Creates new form Resultados
     */
    public Resultados() {
        initComponents();
        this.setBounds(500, 300, this.getWidth(), this.getHeight());
        setLayout(new BorderLayout());
        campo2=new JTextArea();
        scroll=new JScrollPane(campo2);
        add(scroll);
        add(campo2,BorderLayout.CENTER);
        String res;
        res="Condiciones de carga: ";
        res=res+"\n";
        res+=MenuPrincipal.Calculos.getCss()+"\n";
        res+="Acciones de métodos: ";
        res+="\n";
        res+="Vector de racciones en apoyos:";
        res+="\n";
        double[] ar=new double[3*MenuPrincipal.Calculos.getNj()];
        ar=MenuPrincipal.Calculos.getAr();
        for(int i=0;i<ar.length;i++){
            if(i%3==0){
                res+="\n";
            }
            res+=ar[i]+ " ";
        }
        res+="\n";
        res+="Vector de desplazamientos en nudos:";
        res+="\n";
        System.arraycopy(MenuPrincipal.Calculos.getD(),0,ar,0,3*MenuPrincipal.Calculos.getNj()-1);
        for(int i=0;i<3*MenuPrincipal.Calculos.getNj();i++){
            if(i%3==0){
                res+="\n";
            }
            res+=ar[i]+ " ";
        }
        res+="\n";
        res+="Vector de acciones de extremo finales:";
        res+="\n";
        double[][] am=new double[MenuPrincipal.Calculos.getM()][6];
        am=MenuPrincipal.Calculos.getAm();
        for(int i=0;i<MenuPrincipal.Calculos.getM();i++){
            for(int j=0;j<6;j++){
                res+=am[i][j]+ " ";
            }
            res+="\n";
        }
        campo2.setText(res);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resultados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
