
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Panel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alexiyolokooooo
 */
public class DatosDeLaEstructura extends javax.swing.JFrame {
    private ImageIcon imagen,boton;
    private ParametrosDeLaEstructura parametros;
    /**
     * Creates new form DatosDeLaEstructura
     */
    public DatosDeLaEstructura() {
        initComponents();
        this.setBounds(500, 300, this.getWidth(), this.getHeight());
        this.setTitle("DATOS DE LA ESTRUCTURA");
        
        
        setLayout(new BorderLayout());
        Panel q=new Panel( new GridLayout(1,2) );
    
        q.add(jLabel2);  
        q.add(jLabel3); 
        Panel p = new Panel( new GridLayout(7,1) );
        p.add(opcionSecundaria1);
        p.add(opcionSecundaria2);
        p.add(opcionSecundaria3);
        p.add(opcionSecundaria4);
        p.add(opcionSecundaria5);
        p.add(opcionSecundaria6);

        add(p,BorderLayout.CENTER); 
        add(q,BorderLayout.NORTH); 

        imagen= new ImageIcon("src/Imagenes/99.png");
        boton=new ImageIcon(imagen.getImage().getScaledInstance(460, 52, Image.SCALE_DEFAULT));
        opcionSecundaria1.setIcon(boton);
        
        imagen= new ImageIcon("src/Imagenes/10.png");
        boton=new ImageIcon(imagen.getImage().getScaledInstance(460, 52, Image.SCALE_DEFAULT));
        opcionSecundaria2.setIcon(boton);
        
        imagen= new ImageIcon("src/Imagenes/12.png");
        boton=new ImageIcon(imagen.getImage().getScaledInstance(460, 52, Image.SCALE_DEFAULT));
        opcionSecundaria3.setIcon(boton);
        
        imagen= new ImageIcon("src/Imagenes/13.png");
        boton=new ImageIcon(imagen.getImage().getScaledInstance(460, 52, Image.SCALE_DEFAULT));
        opcionSecundaria4.setIcon(boton);
        
        imagen= new ImageIcon("src/Imagenes/14.png");
        boton=new ImageIcon(imagen.getImage().getScaledInstance(460, 52, Image.SCALE_DEFAULT));
        opcionSecundaria5.setIcon(boton);
        
        imagen= new ImageIcon("src/Imagenes/15.png");
        boton=new ImageIcon(imagen.getImage().getScaledInstance(460, 52, Image.SCALE_DEFAULT));
        opcionSecundaria6.setIcon(boton);
        
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        opcionSecundaria1 = new javax.swing.JButton();
        opcionSecundaria2 = new javax.swing.JButton();
        opcionSecundaria3 = new javax.swing.JButton();
        opcionSecundaria4 = new javax.swing.JButton();
        opcionSecundaria5 = new javax.swing.JButton();
        opcionSecundaria6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("<html>*****  OPCIONES :  *****<p><p>"
        );

        jLabel3.setText("<html><p><p><p>De Clic sobre la opcion que desee: ");

        opcionSecundaria1.setText(null);
        opcionSecundaria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionSecundaria1ActionPerformed(evt);
            }
        });

        opcionSecundaria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionSecundaria2ActionPerformed(evt);
            }
        });

        opcionSecundaria3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionSecundaria3ActionPerformed(evt);
            }
        });

        opcionSecundaria4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionSecundaria4ActionPerformed(evt);
            }
        });

        opcionSecundaria5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionSecundaria5ActionPerformed(evt);
            }
        });

        opcionSecundaria6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionSecundaria6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(opcionSecundaria6)
                    .addComponent(opcionSecundaria5)
                    .addComponent(opcionSecundaria4)
                    .addComponent(opcionSecundaria3)
                    .addComponent(opcionSecundaria2)
                    .addComponent(opcionSecundaria1))
                .addContainerGap(295, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(opcionSecundaria1)
                .addGap(18, 18, 18)
                .addComponent(opcionSecundaria2)
                .addGap(18, 18, 18)
                .addComponent(opcionSecundaria3)
                .addGap(18, 18, 18)
                .addComponent(opcionSecundaria4)
                .addGap(18, 18, 18)
                .addComponent(opcionSecundaria5)
                .addGap(18, 18, 18)
                .addComponent(opcionSecundaria6)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jLabel2)
                    .addGap(8, 8, 8)
                    .addComponent(jLabel3)
                    .addContainerGap(252, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionSecundaria6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionSecundaria6ActionPerformed
        MenuPrincipal.getMenu().setVisible(true);
        try{
            parametros.setVisible(false);
        }catch(Exception e){
            
        }

        this.setVisible(false);
        
    }//GEN-LAST:event_opcionSecundaria6ActionPerformed

    private void opcionSecundaria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionSecundaria1ActionPerformed
        parametros= new ParametrosDeLaEstructura();
        if(!parametros.isVisible()){
            parametros.setVisible(true);
        }
    }//GEN-LAST:event_opcionSecundaria1ActionPerformed

    private void opcionSecundaria2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionSecundaria2ActionPerformed
        String coordenadas;
        
        int[][] xy=new int[10][2];
        int pos;
        
        for(int i=0;i<10;i++){
            try{
                 coordenadas = (String) JOptionPane.showInputDialog("Coordenadas del nudo "+(i+1)+" \n por favor ingrese de la forma 'x,y':");
                 pos=coordenadas.lastIndexOf(',');
                 String[] subCoordenada=coordenadas.split(",");
                 xy[i][0]=Integer.parseInt(subCoordenada[0]);
                 
                 xy[i][1]=Integer.parseInt(subCoordenada[1]);
                 System.out.println(xy[i][0]+ " "+xy[i][1]);
            }catch(Exception e){
                i--;
                JOptionPane.showMessageDialog(null, "Error, Ingrese de nuevo porfavor");
            }
           
        }
    }//GEN-LAST:event_opcionSecundaria2ActionPerformed

    private void opcionSecundaria3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionSecundaria3ActionPerformed
        String incidencias;
        
        int[][] xy=new int[10][2];
        
        
        for(int i=0;i<10;i++){
            try{
                 incidencias = (String) JOptionPane.showInputDialog("Incidencias de Miembro "+(i+1)+" \n por favor ingrese de la forma 'nudoInicial,nudoFinal':");
                 
                 String[] subCoordenada=incidencias.split(",");
                 xy[i][0]=Integer.parseInt(subCoordenada[0]);
                 
                 xy[i][1]=Integer.parseInt(subCoordenada[1]);
                 System.out.println(xy[i][0]+ " "+xy[i][1]);
            }catch(Exception e){
                i--;
                JOptionPane.showMessageDialog(null, "Error, Ingrese de nuevo porfavor");
            }
           
        }
    }//GEN-LAST:event_opcionSecundaria3ActionPerformed

    private void opcionSecundaria4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionSecundaria4ActionPerformed
        String elementos,numElemTipo;
        int numElem;
        int[][] elem;
        try{
            x:
            numElemTipo=(String) JOptionPane.showInputDialog("¿Cuántos grupos de elementos tipo hay?");
                numElem = Integer.parseInt(numElemTipo);
                elem= new int[numElem][4];
            for(int i=0;i<numElem;i++){
                try{
                    elementos = (String) JOptionPane.showInputDialog("Grupo# "+(i+1)+" \n por favor ingrese de la forma 'elemInicial,elemFinal,area,momInercia':");
                     
                     String[] subElem=elementos.split(",");
                     elem[i][0]=Integer.parseInt(subElem[0]);
                     elem[i][1]=Integer.parseInt(subElem[1]);
                     elem[i][2]=Integer.parseInt(subElem[2]);
                     elem[i][3]=Integer.parseInt(subElem[3]);
                     System.out.println(elem[i][0]+ " "+elem[i][1]+ " "+elem[i][2]+ " "+elem[i][3]);
                }catch(Exception e){
                    i--;
                    JOptionPane.showMessageDialog(null, "Error, Ingrese de nuevo porfavor");
                }
           
            }
        }catch(Exception e){
            
        }
        
        
        
    }//GEN-LAST:event_opcionSecundaria4ActionPerformed

    private void opcionSecundaria5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionSecundaria5ActionPerformed
        String restricciones,numRestricciones;
        int numRestric;
        int[][] restricc;
        try{
            numRestricciones=(String) JOptionPane.showInputDialog("¿A cuantos nodos desea registrarle restricciones?");
                numRestric = Integer.parseInt(numRestricciones);
                restricc= new int[numRestric][4];
            for(int i=0;i<numRestric;i++){
                try{
                     restricciones = (String) JOptionPane.showInputDialog("Grupo# "+(i+1)+" \n por favor ingrese de la forma 'numNodo,restriccionX,restriccionY,restriccionZ':");
                     
                     String[] subRestricc=restricciones.split(",");
                     restricc[i][0]=Integer.parseInt(subRestricc[0]);
                     restricc[i][1]=Integer.parseInt(subRestricc[1]);
                     restricc[i][2]=Integer.parseInt(subRestricc[2]);
                     restricc[i][3]=Integer.parseInt(subRestricc[3]);
                     System.out.println(restricc[i][0]+ " "+restricc[i][1]+ " "+restricc[i][2]+ " "+restricc[i][3]);
                }catch(Exception e){
                    i--;
                    JOptionPane.showMessageDialog(null, "Error, Ingrese de nuevo porfavor");
                }
           
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_opcionSecundaria5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosDeLaEstructura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosDeLaEstructura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosDeLaEstructura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosDeLaEstructura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new RunnableImpl());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton opcionSecundaria1;
    private javax.swing.JButton opcionSecundaria2;
    private javax.swing.JButton opcionSecundaria3;
    private javax.swing.JButton opcionSecundaria4;
    private javax.swing.JButton opcionSecundaria5;
    private javax.swing.JButton opcionSecundaria6;
    // End of variables declaration//GEN-END:variables

    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {
        }

        @Override
        public void run() {

        }
    }
}
